import path from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import checker from "vite-plugin-checker";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  // Base path:
    //   GitHub Pages: GITHUB_ACTIONS=true (via build:github script) → /Council-Git-V9/
      //   Vercel:       GITHUB_ACTIONS not set → /
        //   Local dev:    GITHUB_ACTIONS not set → /
          const isGitHubPages = process.env.GITHUB_ACTIONS === 'true';
            const base = isGitHubPages ? '/Council-Git-V9/' : '/';

              // Node.js-only packages — never imported by React components.
                // Must be excluded from browser bundle AND dep pre-bundling.
                  const nodeOnlyPackages = [
                      'ts-morph',
                          '@babel/generator',
                              '@babel/parser',
                                  '@babel/traverse',
                                      '@qdrant/js-client-rest',
                                          '@modelcontextprotocol/sdk',
                                            ];

                                              return {
                                                  base,
                                                      server: {
                                                            host: "0.0.0.0",
                                                                  port: 5000,
                                                                        strictPort: true,
                                                                              allowedHosts: true,
                                                                                    cors: true,
                                                                                          middlewareMode: false,
                                                                                                hmr: {
                                                                                                        overlay: true,
                                                                                                                timeout: 30000,
                                                                                                                      },
                                                                                                                            watch: {
                                                                                                                                    ignored: ['**/node_modules/**', '**/dist/**', '**/.git/**'],
                                                                                                                                          },
                                                                                                                                              },
                                                                                                                                                  plugins: [
                                                                                                                                                        react(),
                                                                                                                                                              mode === 'development' && checker({
                                                                                                                                                                      typescript: true,
                                                                                                                                                                              overlay: { initialIsOpen: false },
                                                                                                                                                                                    }),
                                                                                                                                                                                        ].filter(Boolean),
                                                                                                                                                                                            resolve: {
                                                                                                                                                                                                  alias: {
                                                                                                                                                                                                          "@": path.resolve(__dirname, "./src"),
                                                                                                                                                                                                                },
                                                                                                                                                                                                                    },
                                                                                                                                                                                                                        build: {
                                                                                                                                                                                                                              sourcemap: mode === 'development',
                                                                                                                                                                                                                                    rollupOptions: {
                                                                                                                                                                                                                                            external: (id: string) =>
                                                                                                                                                                                                                                                      nodeOnlyPackages.some(pkg => id === pkg || id.startsWith(`${pkg}/`)),
                                                                                                                                                                                                                                                              output: {
                                                                                                                                                                                                                                                                        manualChunks: {
                                                                                                                                                                                                                                                                                    'vendor-mermaid': ['mermaid'],
                                                                                                                                                                                                                                                                                                'vendor-charts': ['recharts'],
                                                                                                                                                                                                                                                                                                            'vendor-ui': [
                                                                                                                                                                                                                                                                                                                          '@radix-ui/react-dialog',
                                                                                                                                                                                                                                                                                                                                        '@radix-ui/react-tabs',
                                                                                                                                                                                                                                                                                                                                                      '@radix-ui/react-select',
                                                                                                                                                                                                                                                                                                                                                                    '@radix-ui/react-tooltip',
                                                                                                                                                                                                                                                                                                                                                                                  '@radix-ui/react-avatar',
                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                          'vendor-react': ['react', 'react-dom', 'react-router-dom', '@tanstack/react-query'],
                                                                                                                                                                                                                                                                                                                                                                                                                      'vendor-utils': ['zustand', 'lucide-react', 'date-fns', 'clsx', 'tailwind-merge'],
                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                onwarn(warning, warn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (warning.code === 'UNUSED_EXTERNAL_IMPORT') return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (warning.code === 'MISSING_EXPORT' && warning.exporter?.includes('ts-morph')) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              warn(warning);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  minify: 'esbuild',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          esbuild: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                drop: mode === 'production' ? ['debugger'] : [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pure: mode === 'production' ? ['console.log', 'console.debug'] : [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              optimizeDeps: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    include: ['react', 'react-dom', 'zustand', 'react-error-boundary'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          exclude: ['@vite/client', '@vite/env', ...nodeOnlyPackages],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });